apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Release.Name }}.{{ .Values.fqdn }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 5000
        path: /
        pathType: Prefix