apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daas-service
  name: daas-service
  namespace: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daas-service
  template:
    metadata:
      labels:
        app: daas-service
    spec:
      serviceAccountName: daas-service
      containers:
      - image: docker.io/christiantragesser/daas
        name: daas-service
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "daas-redis.daas.svc.cluster.local"
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 500M
          requests:
            cpu: 200m
            memory: 100M
