apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daas
  name: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daas
  template:
    metadata:
      labels:
        app: daas
    spec:
      serviceAccountName: daas-services
      containers:
      - image: docker.io/christiantragesser/daas
        name: daas
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 200m
            memory: 500M
