kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filos-service
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - deployments
      - pods
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filos-service
subjects:
- kind: ServiceAccount
  name: filos-service
  namespace: daas
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: filos-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filos-service
  namespace: daas