kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daas-services
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - create
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daas-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: daas-services
subjects:
- kind: ServiceAccount
  name: daas-services
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daas-services