apiVersion: v1
kind: Service
metadata:
  name: daas-redis
  namespace: daas
  labels:
    app: daas-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: db
  selector:
    app: daas-redis