apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: daas
spec:
  ingressClassName: nginx
  rules:
  - host: daas.{{ .Values.fqdn }}
    http:
      paths:
      - backend:
          service:
            name: daas-service
            port:
              number: 5000
        path: /
        pathType: Prefix
