apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daas-redis
  name: daas-redis
  namespace: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daas-redis
  template:
    metadata:
      labels:
        app: daas-redis
    spec:
      containers:
      - image: docker.io/redis
        name: daas-redis
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: 1000m
            memory: 1000M
          requests:
            cpu: 500m
            memory: 500M
