FROM golang:alpine AS source
WORKDIR $GOPATH/src/github.com/christiantragesser/daas
ADD go.mod .
ADD main.go .
ADD alert.go .
ADD pod.go .
RUN go mod tidy

## build ##
FROM source as linux-build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOFLAGS=-buildvcs=false go build \
    -ldflags='-w -s -extldflags "-static"' -a \
    -o /go/bin/daas .

## container image ##
FROM gcr.io/distroless/static AS publish
COPY --from=linux-build /go/bin/daas /usr/local/bin/daas

cmd [ "daas" ]