FROM golang:alpine AS source
WORKDIR $GOPATH/src/github.com/christiantragesser/myapp
ADD go.mod .
ADD main.go .
RUN go mod tidy

## build ##
FROM source as linux-build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOFLAGS=-buildvcs=false go build \
    -ldflags='-w -s -extldflags "-static"' -a \
    -o /go/bin/myapp .

## container image ##
FROM gcr.io/distroless/static AS publish
COPY --from=linux-build /go/bin/myapp /usr/local/bin/myapp

cmd [ "myapp" ]